name: Auto Bump Version

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Bump patch version
      run: |
        FILE="anim_maker_config.json"
        VERSION=$(jq -r '.version' "$FILE")
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        jq --arg v "$NEW_VERSION" '.version = $v' "$FILE" > tmp.json && mv tmp.json "$FILE"
        echo "Bumped to version $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Commit and push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/mlnitoon2/MSM-Config.git
        git add anim_maker_config.json
        git commit -m "Bump version to ${{ env.NEW_VERSION }}" || echo "No changes to commit"
        git push origin HEAD:main
